name: neuron
description: Signal/Slot reactive state management for Flutter. Clean syntax, powerful features including middleware, persistence, time-travel debugging, and code generation support.
version: 1.1.2
homepage: https://github.com/pixeluvw/neuron
repository: https://github.com/pixeluvw/neuron
topics:
  - state-management
  - reactive-programming
  - signals
  - slots
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.0
  shelf_static: ^1.1.0
  web_socket_channel: ^3.0.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # This section identifies your package as a Flutter package
  uses-material-design: false